openapi: 3.0.0
info:
  title: SPP Back-end API
  version: 0.0.1

servers:
  - url: "/api"

paths:
  /:
    get:
      responses:
        "200":
          description: "A list of posts"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
